version: "3.8"

services:
  postgres:
    image: postgres:14.5-alpine
    working_dir: /application
    volumes:
      - postgres:/data/postgres
      - .:/application
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres: