service: kpi-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 128

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-plugin-typescript